# -*- coding: utf-8 -*-
"""Perceptron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qYEGBg6uoXyg6co7cxQo4vOmod5MHT2i

## Modelo do Perceptron
"""

import numpy as np
import time

# definição dos valores de entrada
x1 = np.array([1, -0.1, 0.4, -0.7, -1.8])
x2 = np.array([1, 0.1, 0.2, -0.3, -0.9])

x = [x1,x2]
# definição do valor de saída
y = np.array([1, -1])

# definição do vetor de pesos inicial
w = np.zeros(5)

# definição da taxa de aprendizagem
eta = 0.03
e = np.array([1,1])

while(not all(e == 0)):
  for i in range(0,2):
    vetor_y0 = w*x[i]
    y0 = 1 if sum(vetor_y0) >= 0 else -1
    e[i] = y[i] - y0
  print("O erro é ", e)
  wn = eta*(e[0]*x1 + e[1]*x2)
  w = w + wn
  print("O vetor peso é", w)
  time.sleep(1)

  
print("O vetor peso final é ", w)

